DROP TABLE IF EXISTS LocationEvent;
DROP TABLE IF EXISTS LocationEventURI;
DROP TABLE IF EXISTS PersonalList;
DROP TABLE IF EXISTS PersonalListVendor;
DROP TABLE IF EXISTS Skin;
DROP TABLE IF EXISTS Team;
