#!/usr/bin/env perl

use strict;
use warnings;

use DBIx::Class::Schema::Loader qw( make_schema_at );
make_schema_at(
    'VegGuide::DB',
    {
        dump_directory        => './lib',
        components            => ['InflateColumn::DateTime'],
        use_moose             => 1,
        datetime_timezone     => 'local',                       # XXX - I suck
        custom_column_info    => \&_custom_column_info,
        result_components_map => {
            NewsItem => ['TimeStamp'],
        },
    },
    [
        'dbi:mysql:database=RegVeg', 'root', undef,
    ],
);

sub _custom_column_info {
    my $table  = shift;
    my $column = shift;
    my $info   = shift;

    return unless $column =~ /^(?:creation|last_modified)_datetime$/;

    return {
        set_on_create => 1,
        set_on_update => ( $column eq 'last_modified_datetime' ),
    };
}
